# Generated by Django 5.1.4 on 2025-01-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPLOADED', 'Uploaded'), ('CONFIGS', 'Configs'),
                                            ('PREVIEWS', 'Previews'), ('IN_PROGRESS', 'In Progress'),
                                            ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED',
                                   max_length=20, verbose_name='Status'),
        ),
    ]
