# Generated by Django 5.1.4 on 2025-01-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_batchjob_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskunit',
            name='task_unit_status_a8fc43_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskunitresponse',
            name='task_unit_r_status_1616a7_idx',
        ),
        migrations.RenameField(
            model_name='taskunit',
            old_name='status',
            new_name='task_unit_status',
        ),
        migrations.RenameField(
            model_name='taskunitresponse',
            old_name='status',
            new_name='task_response_status',
        ),
        migrations.RemoveField(
            model_name='batchjob',
            name='status',
        ),
        migrations.AddField(
            model_name='batchjob',
            name='batch_job_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPLOADED', 'Uploaded'), ('CONFIGS', 'Configs'),
                                            ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'),
                                            ('FAILED', 'Failed')], default='CREATED', max_length=20,
                                   verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='taskunit',
            index=models.Index(fields=['task_unit_status'], name='task_unit_task_un_ccab3d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskunitresponse',
            index=models.Index(fields=['task_response_status'], name='task_unit_r_task_re_ae7539_idx'),
        ),
    ]
