# Generated by Django 5.1.4 on 2025-01-08 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_remove_taskunit_task_unit_status_a8fc43_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchjob',
            old_name='config',
            new_name='configs',
        ),
    ]
