# Generated by Django 5.1.4 on 2025-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_rename_config_batchjob_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='batch_job_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPLOADED', 'Uploaded'), ('STANDBY', 'Standby'),
                                            ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'),
                                            ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED',
                                   max_length=20, verbose_name='Status'),
        ),
    ]
