# Generated by Django 5.1.4 on 2025-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_alter_batchjob_batch_job_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskunit',
            name='unique_task_unit_per_batch',
        ),
        migrations.AddIndex(
            model_name='taskunit',
            index=models.Index(fields=['created_at'], name='task_unit_created_793cbc_idx'),
        ),
    ]
