# Generated by Django 5.1.4 on 2025-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_remove_taskunit_unique_task_unit_per_batch_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskunit',
            index=models.Index(fields=['unit_index'], name='task_unit_unit_in_a9db97_idx'),
        ),
    ]
