# Generated by Django 5.1.4 on 2025-01-29 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_taskunit_latest_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['user'], name='batch_job_user_id_4b1108_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['batch_job_status'], name='batch_job_batch_j_769119_idx'),
        ),
    ]
