# Generated by Django 5.1.4 on 2025-01-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_batchjob_batch_job_user_id_4b1108_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskunitresponse',
            name='error_code',
        ),
        migrations.AddField(
            model_name='taskunitresponse',
            name='batch_job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='responses',
                                    to='api.batchjob', verbose_name='Batch Job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskunitresponse',
            name='response_data',
            field=models.JSONField(blank=True, help_text='response data from ChatGPT', null=True,
                                   verbose_name='Response Data'),
        ),
        migrations.AlterField(
            model_name='taskunitresponse',
            name='task_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='responses', to='api.taskunit', verbose_name='Task Unit'),
        ),
        migrations.AddIndex(
            model_name='taskunitresponse',
            index=models.Index(fields=['batch_job'], name='task_unit_r_batch_j_7da424_idx'),
        ),
    ]
