# Generated by Django 5.1.4 on 2025-01-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_remove_taskunitresponse_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskunitresponse',
            name='task_unit_index',
            field=models.PositiveIntegerField(default=1, verbose_name='Task Unit Index'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskunit',
            name='unit_index',
            field=models.PositiveIntegerField(verbose_name='Unit Index'),
        ),
        migrations.AddIndex(
            model_name='taskunitresponse',
            index=models.Index(fields=['task_unit_index'], name='task_unit_r_task_un_ccb5d9_idx'),
        ),
    ]
