# Generated by Django 5.1.4 on 2025-01-29 08:33

import django.db.models.deletion
from django.db import migrations, models

import api.utils.files_processor.file_settings


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_taskunitresponse_task_unit_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskunit',
            name='file_data',
        ),
        migrations.AddField(
            model_name='taskunit',
            name='has_files',
            field=models.BooleanField(default=False, verbose_name='Has Files'),
        ),
        migrations.CreateModel(
            name='TaskUnitFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file_data',
                 models.FileField(upload_to=api.utils.files_processor.file_settings.FileSettings.get_task_unit_path,
                                               verbose_name='File Data')),
                ('task_unit',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.taskunit',
                                   verbose_name='Task Unit')),
            ],
            options={
                'verbose_name': 'Task Unit File',
                'verbose_name_plural': 'Task Unit Files',
                'db_table': 'task_unit_files',
                'indexes': [models.Index(fields=['task_unit'], name='task_unit_f_task_un_e3b47a_idx')],
            },
        ),
    ]
