# Generated by Django 5.1.4 on 2025-01-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_remove_taskunit_file_data_taskunit_has_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskunitfiles',
            name='base64_image_data',
            field=models.TextField(blank=True, null=True, verbose_name='Base64 Image Data'),
        ),
    ]
