# Generated by Django 5.1.4 on 2025-01-31 14:23

from django.db import migrations


def normalize_data(apps, schema_editor):
    TaskUnitResponse = apps.get_model('api', 'TaskUnitResponse')

    for obj in TaskUnitResponse.objects.all():
        from api.utils.gpt_processor.gpt_settings import get_gpt_processor
        gpt_processor = get_gpt_processor(company="openai")
        obj.response_data = gpt_processor.process_response(obj.response_data)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_taskunitfiles_base64_image_data'),
    ]

    operations = [
        migrations.RunPython(normalize_data),
    ]
