services:
  web:
    image: itmir913/batchgpt:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/supervisor
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - db

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - batchgpt_data:/var/lib/postgresql/data

volumes:
  batchgpt_data:
