services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
