# Generated by Django 5.1.4 on 2025-01-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchjob',
            name='prompt',
        ),
        migrations.AddField(
            model_name='batchjob',
            name='config',
            field=models.JSONField(blank=True, null=True, verbose_name='Configurations for BatchJob'),
        ),
    ]
