# Generated by Django 5.1.4 on 2025-01-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('job', '0003_batchjob_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
